services:
  - type: web
    name: streamtracker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: streamtracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: TMDB_API_KEY
        sync: false

  - type: web
    name: streamtracker-frontend
    runtime: static
    staticPublishPath: ./frontend
    buildCommand: ""

databases:
  - name: streamtracker-db
    plan: free
